# Lab Assignment 8: Data Management Using `pandas`, Part 1
## DS 6001: Practice and Application of Data Science

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

In this lab, you will be working with the [2017 Workplace Health in America survey](https://www.cdc.gov/workplacehealthpromotion/survey/data.html) which was conducted by the Centers for Disease Control and Prevention. According to the survey's [guidence document](https://www.cdc.gov/workplacehealthpromotion/data-surveillance/docs/2017-WHA-Guidance-Document-for-Use-of-Public-Data-files-508.pdf):

> The Workplace Health in America (WHA) Survey gathered information from a cross-sectional, nationally representative sample of US worksites. The sample was drawn from the Dun & Bradstreet (D&B) database of all private and public employers in the United States with at least 10 employees. Like previous national surveys, the worksite served as the sampling unit rather than the companies or firms to which the worksites belonged. Worksites were selected using a stratified simple random sample (SRS) design, where the primary strata were ten multi-state regions defined by the Centers for Disease Control and Prevention (CDC), plus an additional stratum containing all hospital worksites. 

The data contain over 300 features that report the industry and type of company where the respondents are employed, what kind of health insurance and other health programs are offered, and other characteristics of the workplaces including whether employees are allowed to work from home and the gender and age makeup of the workforce. The data are full of interesting information, but in order to make use of the data a great deal of data manipulation is required first.

## Problem 0
Import the following libraries:

In [1]:
!pip install sidetable

Requirement already satisfied: sidetable in c:\users\hodge\anaconda3\lib\site-packages (0.9.1)
Requirement already satisfied: pandas>=1.0 in c:\users\hodge\anaconda3\lib\site-packages (from sidetable) (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\hodge\anaconda3\lib\site-packages (from pandas>=1.0->sidetable) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hodge\anaconda3\lib\site-packages (from pandas>=1.0->sidetable) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hodge\anaconda3\lib\site-packages (from pandas>=1.0->sidetable) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hodge\anaconda3\lib\site-packages (from pandas>=1.0->sidetable) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hodge\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0->sidetable) (1.16.0)

In [2]:
import numpy as np
import pandas as pd
import sidetable
import sqlite3
import warnings
warnings.filterwarnings('ignore')

## Problem 1
The raw data are stored in an ASCII file on the 2017 Workplace Health in America survey [homepage](https://www.cdc.gov/workplacehealthpromotion/survey/data.html). Load the raw data directly into Python without downloading the data onto your harddrive and display a dataframe with only the 14th, 28th, and 102nd rows of the data. [1 point]

In [3]:
import json
import requests
import io
from io import StringIO

In [4]:
#load the raw data directly into Python without downloading the data onto your harddrive
url = "https://www.cdc.gov/workplacehealthpromotion/data-surveillance/docs/whpps_120717.csv"
r = requests.get(url)
r

In [5]:
data = r.text

In [6]:
data_io = io.StringIO(data)

df = pd.read_csv(data_io, delimiter = '~')

#display 14th, 28th, and 102nd rows of the data
df.iloc[np.array([13, 27, 101])]

,OC1,OC3,HI1,HI2,HI3,HI4,HRA1,HRA1A,HRA1B,HRA1E,...,WL3_05,E1_09,Suppquex,Id,Region,CDC_Region,Industry,Size,Varstrata,"Finalwt_worksite,,,,"
13,3,1.0,2.0,3.0,2.0,1.0,1.0,3.0,3.0,1.0,...,NaN,NaN,1.0,1437.0,4.0,6.0,7.0,3.0,0.0,"47.793940929,,,,"
27,1,3.0,1.0,3.0,1.0,1.0,1.0,2.0,4.0,2.0,...,NaN,NaN,1.0,2501.0,2.0,4.0,7.0,8.0,0.0,"47.793940929,,,,"
101,2,1.0,1.0,3.0,2.0,1.0,1.0,2.0,4.0,2.0,...,NaN,NaN,2.0,12636.0,4.0,6.0,7.0,4.0,0.0,"47.793940929,,,,"

## Problem 2 
The data contain 301 columns. Create a new variable in Python's memory to store a working version of the data. In the working version, delete all of the columns except for the following:

* `Industry`: 7 Industry Categories with NAICS codes

* `Size`: 8 Employee Size Categories

* `OC3` Is your organization for profit, non-profit, government?

* `HI1` In general, do you offer full, partial or no payment of premiums for personal health insurance for full-time employees?

* `HI2` Over the past 12 months, were full-time employees asked to pay a larger proportion, smaller proportion or the same proportion of personal health insurance premiums?

* `HI3`: Does your organization offer personal health insurance for your part-time employees?

* `CP1`: Are there health education programs, which focus on skill development and lifestyle behavior change along with information dissemination and awareness building?

* `WL6`: Allow employees to work from home?

* Every column that begins `WD`, expressing the percentage of employees that have certain characteristics at the firm

[1 point]

In [7]:
wd_columns = [col for col in df.columns if col.startswith('WD')]

wd_string_list = [str(column) for column in wd_columns]

string_list = ['Industry', 'Size', 'OC3', 'HI1', 'HI2', 'HI3', 'CP1', 'WL6'] + wd_string_list

health_df = df[string_list]

health_df.head()

,Industry,Size,OC3,HI1,HI2,HI3,CP1,WL6,WD1_1,WD1_2,WD2,WD3,WD4,WD5,WD6,WD7
0,7.0,7.0,3.0,2.0,1.0,2.0,1.0,1.0,25.0,20.0,85.0,60.0,40.0,15.0,0.0,22.0
1,7.0,6.0,3.0,2.0,3.0,1.0,1.0,1.0,997.0,997.0,90.0,90.0,997.0,997.0,0.0,997.0
2,7.0,8.0,3.0,1.0,3.0,1.0,1.0,1.0,35.0,4.0,997.0,997.0,40.0,15.0,997.0,997.0
3,7.0,4.0,2.0,1.0,2.0,1.0,2.0,2.0,50.0,15.0,50.0,85.0,75.0,0.0,0.0,997.0
4,7.0,4.0,3.0,1.0,3.0,1.0,1.0,1.0,50.0,40.0,60.0,60.0,40.0,30.0,0.0,28.0

## Problem 3
The [codebook](https://www.cdc.gov/workplacehealthpromotion/data-surveillance/docs/2017-WHA-Datafile-Codebook-508.pdf) for the WHA data contain short descriptions of the meaning of each of the columns in the data. Use these descriptions to decide on better and more intuitive names for the columns in the working version of the data, and rename the columns accordingly. [1 point]

In [8]:
updated_columns = {'OC3' : 'Organization_Status',
            'HI1' : 'Insurance_Coverage',
            'HI2' : 'Payment_Size',
            'HI3' : 'Health_Insurance_Offered',
            'CP1' : 'Health_Education_Offered',
            'WL6' : 'At_Home_Workers',
            'WD1_1' : 'Workers_Under_30(%)',
            'WD1_2' : 'Workers_60_and_Older(%)',
            'WD2': 'Female_Workers(%)',
            'WD3' : 'Hourly/Non-Exempt_Workers(%)',
            'WD4' : 'Non-Daytime_Workers(%)',
            'WD5' : 'Remote/Off-site_Workers(%)',
            'WD6' : 'Bargaining/Unionized_Workers(%)',
            'WD7' : 'Annual_Empoloyee_Turnover(%)'}

health_df = health_df.rename(columns = updated_columns)

health_df

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%)
0,7.0,7.0,3.0,2.0,1.0,2.0,1.0,1.0,25.0,20.0,85.0,60.0,40.0,15.0,0.0,22.0
1,7.0,6.0,3.0,2.0,3.0,1.0,1.0,1.0,997.0,997.0,90.0,90.0,997.0,997.0,0.0,997.0
2,7.0,8.0,3.0,1.0,3.0,1.0,1.0,1.0,35.0,4.0,997.0,997.0,40.0,15.0,997.0,997.0
3,7.0,4.0,2.0,1.0,2.0,1.0,2.0,2.0,50.0,15.0,50.0,85.0,75.0,0.0,0.0,997.0
4,7.0,4.0,3.0,1.0,3.0,1.0,1.0,1.0,50.0,40.0,60.0,60.0,40.0,30.0,0.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2838,6.0,5.0,4.0,1.0,3.0,1.0,1.0,99.0,999.0,999.0,999.0,999.0,999.0,999.0,999.0,999.0
2839,6.0,5.0,4.0,2.0,3.0,1.0,1.0,2.0,997.0,997.0,997.0,997.0,997.0,997.0,997.0,997.0
2840,6.0,8.0,4.0,2.0,3.0,1.0,1.0,1.0,27.0,997.0,61.0,997.0,997.0,997.0,997.0,997.0
2841,6.0,8.0,4.0,2.0,3.0,1.0,2.0,99.0,999.0,999.0,999.0,999.0,999.0,999.0,999.0,999.0
2842,6.0,8.0,4.0,2.0,3.0,1.0,1.0,1.0,25.0,10.0,35.0,90.0,25.0,60.0,80.0,997.0

## Problem 4
Using the codebook and this [dictionary of NAICS industrial codes](https://www.naics.com/search-naics-codes-by-industry/), place descriptive labels on the categories of the industry column in the working data. [1 point]

In [9]:
health_df['Industry'].unique()

array([ 7.,  1.,  2.,  3.,  4.,  5.,  6., nan])

In [10]:
health_df['Industry']

0       7.0
1       7.0
2       7.0
3       7.0
4       7.0
       ...
2838    6.0
2839    6.0
2840    6.0
2841    6.0
2842    6.0
Name: Industry, Length: 2843, dtype: float64

In [11]:
industry_mapping = {
    1: 'Agriculture, Forestry, Fishing and Hungting; Mining; Utilities; Construction; Manufacturing',
    2: 'Wholesale Trade; Retail Trade; Transportation and Warehousing',
    3: 'Arts, Entertainment, and Recreation; Accomodation and Food Services; Other Services (except Public Adminitration)',
    4: 'Information; Finance and Insurance; Real Estate Rental and Leasing; Professional, Scientific, and Technical Services; Management of Compoanies and Enterprises; Adminitrative and Support and Waste...Services',
    5: 'Educational Services; Health Care and Social Assistance (excluding hospitalworksites)',
    6: 'Public Administration',
    7: 'General Medical and Surgical Hospitals; Psychiatric and Substance Abuse Hospitals; Specialty (except Psychiatric and Substance Abuse) Hospitals',
    'nan': np.nan
}

industry_mapping = {
    1: {11: 'Agriculture, Forestry, Fishing and Hungting', 21: 'Mining', 22: 'Utilities', 23: 'Construction', 31-33: 'Manufacturing'},
    2: {42: 'Wholesale Trade', 44-45: 'Retail Trade', 48-49: 'Transportation and Warehousing'},
    3: {71: 'Arts, Entertainment, and Recreation', 72: 'Accomodation and Food Services', 81: 'Other Services (except Public Adminitration)'},
    4: {51: 'Information', 52: 'Finance and Insurance', 53: 'Real Estate Rental and Leasing', 54: 'Professional, Scientific, and Technical Services', 55: 'Management of Compoanies and Enterprises', 56: 'Adminitrative and Support and Waste...Services'},
    5: {61: 'Educational Services', 62: 'Health Care and Social Assistance (excluding hospitalworksites)'},
    6: {92: 'Public Administration'},
    7: {622110: 'General Medical and Surgical Hospitals', 622210: 'Psychiatric and Substance Abuse Hospitals', 622310: 'Specialty (except Psychiatric and Substance Abuse) Hospitals'},
    'nan': np.nan
}

> I don't know any other way to solve this problem than treating this as a "Recoding Many Categorical Columns At Once" problem.

In [12]:
health_df['Industry'] = health_df['Industry'].map(industry_mapping)

health_df['Industry']

0       General Medical and Surgical Hospitals; Psychi...
1       General Medical and Surgical Hospitals; Psychi...
2       General Medical and Surgical Hospitals; Psychi...
3       General Medical and Surgical Hospitals; Psychi...
4       General Medical and Surgical Hospitals; Psychi...
                              ...
2838                                Public Administration
2839                                Public Administration
2840                                Public Administration
2841                                Public Administration
2842                                Public Administration
Name: Industry, Length: 2843, dtype: object

> I had to call to .map() instead of .replace() because I was getting an attribute error that said

```python
AttributeError: 'Series' object has no attribute '_replace_columnwise'
```

> I therefore had to continue with .map()

In [13]:
health_df.head()

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%)
0,General Medical and Surgical Hospitals; Psychi...,7.0,3.0,2.0,1.0,2.0,1.0,1.0,25.0,20.0,85.0,60.0,40.0,15.0,0.0,22.0
1,General Medical and Surgical Hospitals; Psychi...,6.0,3.0,2.0,3.0,1.0,1.0,1.0,997.0,997.0,90.0,90.0,997.0,997.0,0.0,997.0
2,General Medical and Surgical Hospitals; Psychi...,8.0,3.0,1.0,3.0,1.0,1.0,1.0,35.0,4.0,997.0,997.0,40.0,15.0,997.0,997.0
3,General Medical and Surgical Hospitals; Psychi...,4.0,2.0,1.0,2.0,1.0,2.0,2.0,50.0,15.0,50.0,85.0,75.0,0.0,0.0,997.0
4,General Medical and Surgical Hospitals; Psychi...,4.0,3.0,1.0,3.0,1.0,1.0,1.0,50.0,40.0,60.0,60.0,40.0,30.0,0.0,28.0

## Problem 5
Using the codebook, recode the "size" column to have three categories: "Small" for workplaces with fewer than 100 employees, "Medium" for workplaces with at least 100 but fewer than 500 employees, and "Large" for companies with at least 500 employees. [Note: Python dataframes have an attribute `.size` that reports the space the dataframe takes up in memory. Don't confuse this attribute with the column named "Size" in the raw data.] [1 point]

In [14]:
size_remapping = {1: 'Small',
                 2: 'Small',
                 3: 'Small',
                 4: 'Medium',
                 5: 'Medium',
                 6: 'Large',
                 7: 'Large',
                 8: 'Large'}

health_df['Size'] = health_df['Size'].map(size_remapping)

health_df['Size']

0        Large
1        Large
2        Large
3       Medium
4       Medium
         ...
2838    Medium
2839    Medium
2840     Large
2841     Large
2842     Large
Name: Size, Length: 2843, dtype: object

In [15]:
health_df.head()

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%)
0,General Medical and Surgical Hospitals; Psychi...,Large,3.0,2.0,1.0,2.0,1.0,1.0,25.0,20.0,85.0,60.0,40.0,15.0,0.0,22.0
1,General Medical and Surgical Hospitals; Psychi...,Large,3.0,2.0,3.0,1.0,1.0,1.0,997.0,997.0,90.0,90.0,997.0,997.0,0.0,997.0
2,General Medical and Surgical Hospitals; Psychi...,Large,3.0,1.0,3.0,1.0,1.0,1.0,35.0,4.0,997.0,997.0,40.0,15.0,997.0,997.0
3,General Medical and Surgical Hospitals; Psychi...,Medium,2.0,1.0,2.0,1.0,2.0,2.0,50.0,15.0,50.0,85.0,75.0,0.0,0.0,997.0
4,General Medical and Surgical Hospitals; Psychi...,Medium,3.0,1.0,3.0,1.0,1.0,1.0,50.0,40.0,60.0,60.0,40.0,30.0,0.0,28.0

## Problem 6
Use the codebook to write accurate and descriptive labels for each category for each categorical column in the working data. Then apply all of these labels to the data at once. Code "Legitimate Skip", "Don't know", "Refused", and "Blank" as missing values. [2 points]

In [16]:
updated_columns

{'OC3': 'Organization_Status',
 'HI1': 'Insurance_Coverage',
 'HI2': 'Payment_Size',
 'HI3': 'Health_Insurance_Offered',
 'CP1': 'Health_Education_Offered',
 'WL6': 'At_Home_Workers',
 'WD1_1': 'Workers_Under_30(%)',
 'WD1_2': 'Workers_60_and_Older(%)',
 'WD2': 'Female_Workers(%)',
 'WD3': 'Hourly/Non-Exempt_Workers(%)',
 'WD4': 'Non-Daytime_Workers(%)',
 'WD5': 'Remote/Off-site_Workers(%)',
 'WD6': 'Bargaining/Unionized_Workers(%)',
 'WD7': 'Annual_Empoloyee_Turnover(%)'}

In [17]:
replace_map = {'Organization_Status':{1: 'For profit, public', 2: 'For profit, private', 3: 'Non-profit', 4: 'State or local government', 5: 'Federal government', 6: 'Other'},
               'Insurance_Coverage': {1: 'Full insurance coverage offered', 2: 'Partial insurance coverage offered', 3: 'No insurance coverage offered'},
               'Payment_Size': {1: 'Larger', 2: 'Smaller', 3:'About the same'},
               'Health_Insurance_Offered': {1:'Yes', 2:'No'},
               'Health_Education_Offered': {1:'Yes', 2:'No'},
               'At_Home_Workers': {1:'Yes', 2:'No'}
               
    
}

#missing_values = {97:np.nan, 98:np.nan, 99:np.nan}
health_df = health_df.replace(replace_map)

health_df = health_df.replace([97, 98, 99], np.nan)

health_df.head()

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%)
0,General Medical and Surgical Hospitals; Psychi...,Large,Non-profit,Partial insurance coverage offered,Larger,No,Yes,Yes,25.0,20.0,85.0,60.0,40.0,15.0,0.0,22.0
1,General Medical and Surgical Hospitals; Psychi...,Large,Non-profit,Partial insurance coverage offered,About the same,Yes,Yes,Yes,997.0,997.0,90.0,90.0,997.0,997.0,0.0,997.0
2,General Medical and Surgical Hospitals; Psychi...,Large,Non-profit,Full insurance coverage offered,About the same,Yes,Yes,Yes,35.0,4.0,997.0,997.0,40.0,15.0,997.0,997.0
3,General Medical and Surgical Hospitals; Psychi...,Medium,"For profit, private",Full insurance coverage offered,Smaller,Yes,No,No,50.0,15.0,50.0,85.0,75.0,0.0,0.0,997.0
4,General Medical and Surgical Hospitals; Psychi...,Medium,Non-profit,Full insurance coverage offered,About the same,Yes,Yes,Yes,50.0,40.0,60.0,60.0,40.0,30.0,0.0,28.0

## Problem 7
The features that measure the percent of the workforce with a particular characteristic use the codes 997, 998, and 999 to represent "Don't know", "Refusal", and "Blank/Invalid" respectively. Replace these values with missing values for all of the percentage features at the same time. [1 point]

In [18]:
#missing_values = {97:np.nan, 98:np.nan, 99:np.nan}
health_df = health_df.replace([997, 998, 999], np.nan)

health_df.head()

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%)
0,General Medical and Surgical Hospitals; Psychi...,Large,Non-profit,Partial insurance coverage offered,Larger,No,Yes,Yes,25.0,20.0,85.0,60.0,40.0,15.0,0.0,22.0
1,General Medical and Surgical Hospitals; Psychi...,Large,Non-profit,Partial insurance coverage offered,About the same,Yes,Yes,Yes,NaN,NaN,90.0,90.0,NaN,NaN,0.0,NaN
2,General Medical and Surgical Hospitals; Psychi...,Large,Non-profit,Full insurance coverage offered,About the same,Yes,Yes,Yes,35.0,4.0,NaN,NaN,40.0,15.0,NaN,NaN
3,General Medical and Surgical Hospitals; Psychi...,Medium,"For profit, private",Full insurance coverage offered,Smaller,Yes,No,No,50.0,15.0,50.0,85.0,75.0,0.0,0.0,NaN
4,General Medical and Surgical Hospitals; Psychi...,Medium,Non-profit,Full insurance coverage offered,About the same,Yes,Yes,Yes,50.0,40.0,60.0,60.0,40.0,30.0,0.0,28.0

## Problem 8
Sort the working data by industry in ascending alphabetical order. Within industry categories, sort the rows by size in ascending alphabetical order. Within groups with the same industry and size, sort by percent of the workforce that is under 30 in descending numeric order. [1 point]

In [19]:
health_df = health_df.sort_values(by = ['Industry', 'Size', 'Workers_Under_30(%)'], ascending = [True, True, False])
health_df

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%)
1732,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Partial insurance coverage offered,About the same,No,Yes,No,50.0,10.0,50.0,75.0,10.0,0.0,0.0,75.0
1476,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Partial insurance coverage offered,About the same,No,Yes,No,40.0,10.0,30.0,60.0,30.0,5.0,0.0,10.0
1477,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Partial insurance coverage offered,Smaller,No,Yes,Yes,25.0,15.0,20.0,60.0,10.0,2.0,60.0,5.0
704,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Full insurance coverage offered,About the same,No,Yes,Yes,20.0,15.0,17.0,62.0,10.0,5.0,0.0,11.0
1241,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Full insurance coverage offered,About the same,No,Yes,Yes,20.0,25.0,50.0,70.0,20.0,5.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2604,Wholesale Trade; Retail Trade; Transportation ...,Small,Non-profit,Full insurance coverage offered,About the same,No,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2626,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, private",Partial insurance coverage offered,Larger,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2629,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, public",Full insurance coverage offered,Larger,No,Yes,Yes,NaN,2.0,15.0,NaN,NaN,90.0,0.0,15.0
2631,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, private",Partial insurance coverage offered,Larger,Yes,No,No,NaN,NaN,NaN,95.0,NaN,NaN,NaN,NaN
1662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Problem 9
There is one row in the working data that has a `NaN` value for industry. Delete this row. Use a logical expression, and not the row number. [1 point]

In [20]:
health_df = health_df.dropna(subset = ['Industry'])
health_df

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%)
1732,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Partial insurance coverage offered,About the same,No,Yes,No,50.0,10.0,50.0,75.0,10.0,0.0,0.0,75.0
1476,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Partial insurance coverage offered,About the same,No,Yes,No,40.0,10.0,30.0,60.0,30.0,5.0,0.0,10.0
1477,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Partial insurance coverage offered,Smaller,No,Yes,Yes,25.0,15.0,20.0,60.0,10.0,2.0,60.0,5.0
704,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Full insurance coverage offered,About the same,No,Yes,Yes,20.0,15.0,17.0,62.0,10.0,5.0,0.0,11.0
1241,"Agriculture, Forestry, Fishing and Hungting; M...",Large,"For profit, private",Full insurance coverage offered,About the same,No,Yes,Yes,20.0,25.0,50.0,70.0,20.0,5.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, private",Full insurance coverage offered,About the same,Yes,No,No,NaN,2.0,2.0,90.0,0.0,0.0,0.0,0.0
2604,Wholesale Trade; Retail Trade; Transportation ...,Small,Non-profit,Full insurance coverage offered,About the same,No,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2626,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, private",Partial insurance coverage offered,Larger,Yes,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2629,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, public",Full insurance coverage offered,Larger,No,Yes,Yes,NaN,2.0,15.0,NaN,NaN,90.0,0.0,15.0
2631,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, private",Partial insurance coverage offered,Larger,Yes,No,No,NaN,NaN,NaN,95.0,NaN,NaN,NaN,NaN

## Problem 10
Create a new feature named `gender_balance` that has three categories: "Mostly men" for workplaces with between 0% and 35% female employees, "Balanced" for workplaces with more than 35% and at most 65% female employees, and "Mostly women" for workplaces with more than 65% female employees. [1 point]

In [21]:
health_df['gender_balance'] = pd.cut(health_df['Female_Workers(%)'], bins = [-0.1, 35, 65, 100], labels = ('Mostly men', 'Balanced', 'Mostly women'))
health_df[['Female_Workers(%)', 'gender_balance']]

      Female_Workers(%) gender_balance
1732               50.0       Balanced
1476               30.0     Mostly men
1477               20.0     Mostly men
704                17.0     Mostly men
1241               50.0       Balanced
...                 ...            ...
2595                2.0     Mostly men
2604                NaN            NaN
2626                NaN            NaN
2629               15.0     Mostly men
2631                NaN            NaN

[2842 rows x 2 columns]

## Problem 11
Change the data type of all categorical features in the working data from "object" to "category". [1 point]

In [22]:
updated_columns

{'OC3': 'Organization_Status',
 'HI1': 'Insurance_Coverage',
 'HI2': 'Payment_Size',
 'HI3': 'Health_Insurance_Offered',
 'CP1': 'Health_Education_Offered',
 'WL6': 'At_Home_Workers',
 'WD1_1': 'Workers_Under_30(%)',
 'WD1_2': 'Workers_60_and_Older(%)',
 'WD2': 'Female_Workers(%)',
 'WD3': 'Hourly/Non-Exempt_Workers(%)',
 'WD4': 'Non-Daytime_Workers(%)',
 'WD5': 'Remote/Off-site_Workers(%)',
 'WD6': 'Bargaining/Unionized_Workers(%)',
 'WD7': 'Annual_Empoloyee_Turnover(%)'}

In [23]:
health_df.dtypes

Industry                             object
Size                                 object
Organization_Status                  object
Insurance_Coverage                   object
Payment_Size                         object
Health_Insurance_Offered             object
Health_Education_Offered             object
At_Home_Workers                      object
Workers_Under_30(%)                 float64
Workers_60_and_Older(%)             float64
Female_Workers(%)                   float64
Hourly/Non-Exempt_Workers(%)        float64
Non-Daytime_Workers(%)              float64
Remote/Off-site_Workers(%)          float64
Bargaining/Unionized_Workers(%)     float64
Annual_Empoloyee_Turnover(%)        float64
gender_balance                     category
dtype: object

In [24]:
catcolumns = ['Organization_Status', 'Insurance_Coverage', 'Payment_Size', 'Health_Insurance_Offered', 'Health_Education_Offered', 'At_Home_Workers']

health_df[catcolumns] = health_df[catcolumns].astype('category')

health_df.dtypes

Industry                             object
Size                                 object
Organization_Status                category
Insurance_Coverage                 category
Payment_Size                       category
Health_Insurance_Offered           category
Health_Education_Offered           category
At_Home_Workers                    category
Workers_Under_30(%)                 float64
Workers_60_and_Older(%)             float64
Female_Workers(%)                   float64
Hourly/Non-Exempt_Workers(%)        float64
Non-Daytime_Workers(%)              float64
Remote/Off-site_Workers(%)          float64
Bargaining/Unionized_Workers(%)     float64
Annual_Empoloyee_Turnover(%)        float64
gender_balance                     category
dtype: object

## Problem 12
Filter the data to only those rows that represent small workplaces that allow employees to work from home. Then report how many of these workplaces offer full insurance, partial insurance, and no insurance. Use a function that reports the percent, cumulative count, and cumulative percent in addition to the counts. [1 point]

In [ ]:
health_df.stb.freq([])

In [32]:
query_df = health_df.query("Size == 'Small' & At_Home_Workers == 'Yes'")
query_df

,Industry,Size,Organization_Status,Insurance_Coverage,Payment_Size,Health_Insurance_Offered,Health_Education_Offered,At_Home_Workers,Workers_Under_30(%),Workers_60_and_Older(%),Female_Workers(%),Hourly/Non-Exempt_Workers(%),Non-Daytime_Workers(%),Remote/Off-site_Workers(%),Bargaining/Unionized_Workers(%),Annual_Empoloyee_Turnover(%),gender_balance
900,"Agriculture, Forestry, Fishing and Hungting; M...",Small,NaN,No insurance coverage offered,96.0,No,No,Yes,100.0,0.0,90.0,90.0,1.0,1.0,0.0,80.0,Mostly women
2051,"Agriculture, Forestry, Fishing and Hungting; M...",Small,"For profit, private",Full insurance coverage offered,About the same,No,No,Yes,95.0,1.0,1.0,50.0,50.0,5.0,0.0,30.0,Mostly men
542,"Agriculture, Forestry, Fishing and Hungting; M...",Small,"For profit, private",Partial insurance coverage offered,About the same,No,No,Yes,90.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1180,"Agriculture, Forestry, Fishing and Hungting; M...",Small,"For profit, private",Full insurance coverage offered,About the same,No,No,Yes,75.0,1.0,5.0,5.0,0.0,75.0,0.0,5.0,Mostly men
2577,"Agriculture, Forestry, Fishing and Hungting; M...",Small,"For profit, private",Partial insurance coverage offered,About the same,No,No,Yes,75.0,4.0,1.0,75.0,30.0,5.0,0.0,20.0,Mostly men
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1768,Wholesale Trade; Retail Trade; Transportation ...,Small,Other,Partial insurance coverage offered,NaN,Yes,NaN,Yes,NaN,NaN,15.0,80.0,NaN,NaN,NaN,NaN,Mostly men
2109,Wholesale Trade; Retail Trade; Transportation ...,Small,NaN,Partial insurance coverage offered,Smaller,No,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2112,Wholesale Trade; Retail Trade; Transportation ...,Small,Other,Full insurance coverage offered,About the same,No,No,Yes,NaN,NaN,NaN,NaN,0.0,5.0,NaN,NaN,NaN
2384,Wholesale Trade; Retail Trade; Transportation ...,Small,NaN,NaN,96.0,Yes,Yes,Yes,NaN,NaN,NaN,20.0,NaN,NaN,NaN,1.0,NaN
2629,Wholesale Trade; Retail Trade; Transportation ...,Small,"For profit, public",Full insurance coverage offered,Larger,No,Yes,Yes,NaN,2.0,15.0,NaN,NaN,90.0,0.0,15.0,Mostly men

In [33]:
query_df.stb.freq(['Insurance_Coverage'])

,Insurance_Coverage,count,percent,cumulative_count,cumulative_percent
0,Full insurance coverage offered,324,46.285714,324,46.285714
1,Partial insurance coverage offered,310,44.285714,634,90.571429
2,No insurance coverage offered,66,9.428571,700,100.000000

## Problem 13
Anything that can be done in SQL can be done with `pandas`. The next several questions ask you to write `pandas` code to match a given SQL query. But to check that the SQL query and `pandas` code yield the same result, create a new database wsing the `sqlite3` package and input the cleaned WHA data as a table in this database. (See module 6 for a discussion of SQlite in Python.) [1 point]

## Problem 14
Write `pandas` code that replicates the output of the following SQL code:
```
SELECT size, type, premiums AS insurance, percent_female FROM whpps
WHERE industry = 'Hospitals' AND premium_change='Smaller'
ORDER BY percent_female DESC;
```
For each of these queries, your feature names might be different from the ones listed in the query, depending on the names you chose in problem 3.
[2 points]

## Problem 15
Write `pandas` code that replicates the output of the following SQL code:
```
SELECT industry, 
    AVG(percent_female) as percent_female, 
    AVG(percent_under30) as percent_under30,
    AVG(percent_over60) as percent_over60
FROM whpps
GROUP BY industry
ORDER BY percent_female DESC;
```
[2 points]

## Problem 16
Write `pandas` code that replicates the output of the following SQL code:
```
SELECT gender_balance, premiums, COUNT(*)
FROM whpps
GROUP BY gender_balance, premiums
HAVING gender_balance is NOT NULL and premiums is NOT NULL;
```
[2 points]